language: cpp
compiler:
    - gcc
notifications:
    email: false
env:
    - JULIAVERSION="julianightlies"
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
    - sudo apt-get update -qq -y
    - sudo apt-get install julia -y
    - sudo apt-get install gfortran liblapack-dev
    - sudo apt-get install libgmp-dev -y
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("RationalSimplex"))`); cd(Pkg.dir("RationalSimplex"))'
    - julia --code-coverage test/runtests.jl
    - julia -e 'Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'